### ISSUE TITLE
Crash after deleting message

### ISSUE THREAD

**Issue by arterialist** [arterialist/core_messenger#11]
App crashes when user edits message and tries to delete it.

Stack trace:
```
Traceback (most recent call last):
  File "main.py", line 271, in <lambda>
    delete_action.triggered.connect(lambda: delete_message_item_selected_callback(self.messages_list, message_item))
  File "core_messenger/callback/callbacks.py", line 173, in delete_message_item_selected_callback
    client_base.send_message(Packet(action=DeleteMessageAction(), message=delete_message_msg))
  File "core_messenger/client/client_base.py", line 174, in send_message
    layers.socket_send_data(current_connection, message, loaded_modules)
  File "core_messenger/client/layers.py", line 9, in socket_send_data
    what = action.process(what)
  File "core_messenger/client/modules/default_modules.py", line 38, in process
    data.message.text = base64.b64encode(data.message.text.encode()).decode()
AttributeError: 'NoneType' object has no attribute 'encode'
```

Reason: no `text` field check in Base64EncodeModule

**Comment by arterialist** [comment]
done
