### ISSUE TITLE
Crash if no route to host

### ISSUE THREAD

**Issue by arterialist** [arterialist/core_messenger#12]
Stack trace:
```
Traceback (most recent call last):
  File "core_messenger/widgets/dialogs/dialogs_head.py", line 32, in <lambda>
    self.new_dialog_button.clicked.connect(lambda: new_dialog_click_callback(self))
  File "core_messenger/callback/callbacks.py", line 36, in new_dialog_click_callback
    client_base.p2p_connect(host, int(port))
  File "core_messenger/client/client_base.py", line 128, in p2p_connect
    sock.connect(current_connection_address)
OSError: [Errno 113] No route to host
```

**Comment by arterialist** [comment]
fixed in multiconnect client_core
